### ISSUE TITLE
Decide how to display graphs

### ISSUE THREAD

**Issue by LeVoid** [jexxme/vBull#1]
### Option A
Build one canvas / graph per company.
This will retain the delta-coloring (green for rising, red for falling).

### Option B
Overlay all graphs overtop of one another, but with different colours for each company.
This will get rid of the delta-color.

### Option C
If you have another option off the top of your head.

**Comment by LeVoid** [comment]
@jexxme choice is yours

**Comment by jexxme** [comment]
A looks awesome :)
