### ISSUE TITLE
Make graphs continue updating

### ISSUE THREAD

**Issue by LeVoid** [jexxme/vBull#2]
As of now, graphs just clear entirely once the right side of the graph was reached.
This should change to the point where the graph effectively scrolls to the right when space runs thin.

**Comment by LeVoid** [comment]
This change includes keeping track of all n latest points which could become quite performance intensive (for client-side, js).

**Comment by jexxme** [comment]
I guess u fixed it?

**Comment by LeVoid** [comment]
Oh yeah, forgot to close this one.

195d2e4 concludes this issue.
