### ISSUE TITLE
Cap for stock value?

### ISSUE THREAD

**Issue by LeVoid** [jexxme/vBull#4]
Maybe implement a max value (per company) that the stock price will cap at.

Reason being: I observed AutoTech to get a value of 4900 natutally. The graph maxes out at 400 though...

Alternatively we could make the graph scroll up / down to reflect the newest value. (Big effort and possibly huge performance impact though)

**Comment by LeVoid** [comment]
![image](https://github.com/jexxme/vBull/assets/71784437/06c98e69-9c82-431e-9936-6f9617f41fc4)

I mean, look at the boi skyrocketing himself out of existance xD

**Comment by jexxme** [comment]
Idk how AutoTech managed to climb up there, lol

I feel like capping the stocks would be a Hack for a problem were too lazy to solve. 

What about a scaling Graph like in this example: 
https://www.bloomberg.com/features/2015-stock-chart-trading-game/

(Btw just found the game, pretty cool implementation of this idea)

**Comment by LeVoid** [comment]
The game from the link doesn't show scaling, but rather "follow the current price around the y-axis".
That is a fair way to solve it though, but we will need height-numbers, indicating the price, like your example does.

Real scaling doesn't work though, as the chart is way too small to be able to identify anything, as 0 will always be 0 and the max will be the maximum price (which sometimes may be 4000).

**Comment by LeVoid** [comment]
Referencing #9 here, as this might solve the issue

**Comment by jexxme** [comment]
> Referencing #9 and #10 here, as chartjs may solve this issue

It does, in my testing the charts automatically scale up / down! :)

**Comment by jexxme** [comment]
We can also modify the dataset to for data be removed after x units, so the scaling isnt looking off after a while

**Comment by jexxme** [comment]
> ![image](https://private-user-images.githubusercontent.com/71784437/301157952-06c98e69-9c82-431e-9936-6f9617f41fc4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczMzIyMjQsIm5iZiI6MTcwNzMzMTkyNCwicGF0aCI6Ii83MTc4NDQzNy8zMDExNTc5NTItMDZjOThlNjktOWM4Mi00MzFlLTk5MzYtNmY5NjE3ZjQxZmM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA3VDE4NTIwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNjMjU2NTgyOTlhYjE2Yjc1MDY5OWJjZWYzNWMyMjAyOWI0YjQyYTY5ZTk2YjllZGQzNzdmMGUzOWJiODU1YWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MH31xuoqfJAJSl5t6tUz-LYmZzsHEY0ZYRhgwW5R9Yg)
> 
> I mean, look at the boi skyrocketing himself out of existance xD

btw i tried to fix this in the chart.js branch (fucked up there lol)
