### ISSUE TITLE
Bootstrap css styling

### ISSUE THREAD

**Issue by LeVoid** [jexxme/vBull#8]
Bootstrap sets a lot of properties for styling. For example we can't change the background color, because it's determined by bootstrap to be #fff.

We need some way to deal with this.

**Comment by jexxme** [comment]
A: Remove BS 
B: Fix in SCSS
C: Do nothing about it

I prefer A

**Comment by LeVoid** [comment]
Yea, same here.
So A it is.

**Comment by LeVoid** [comment]
Done in #11
