### ISSUE TITLE
Q: p5.js advantages?

### ISSUE THREAD

**Issue by jexxme** [jexxme/vBull#9]
Hiya, was looking into p5 more. Damn, what a mighty Toolset. Isnt it a bit too mighty for us? 

Found chart.js's  "Progressive Line" Animation and im in love...

https://www.chartjs.org/docs/latest/samples/animations/progressive-line.html

Generally Chart.js seems sooooooooo nice, but gives less freedom...

How fixated on p5 js are we? :D

**Comment by LeVoid** [comment]
We've built the first initial graph in p5 and modularized it to the point where we can easily slot in and out new graphs and companies (see readme for more details on adding these).

We can change though and maybe modularize the chart.js approach to the same extend. Shouldn't be much harder.

One good resource for p5 is [the coding train](https://www.youtube.com/@TheCodingTrain) on youtube. This might be usable as a documentation to go back to if we want to expand using p5.

**Comment by jexxme** [comment]
Aight, I'm really in love with chart.js rn, I'll try to get to the same point we are currently with j5. 
If chart.js is giving me too much of a headache ill dump this idea ;)

**Comment by jexxme** [comment]
Looked more into chart.js, still in love... 

Implemented a prototype in [7da74d7](https://github.com/jexxme/vBull/commit/7da74d7636a05d5b3ca5c10aa9b6d9e0ded8ab2d)

If I can get the protoype to look like [this](https://nagix.github.io/chartjs-plugin-streaming/master/samples/integration/financial.html), I'm freakin sold on it. Whats your opinion?

**Comment by LeVoid** [comment]
Yeah I'm sold, let's switch.
Let's use #10 for the migration.
